# Generated by Django 3.0.4 on 2020-04-01 05:13

from django.db import migrations, models
import django.db.models.deletion
import e_learning.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='text')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='reason')),
                ('is_correct', models.BooleanField(default=False, verbose_name='is the correct answer')),
            ],
            options={
                'verbose_name': 'answer',
                'verbose_name_plural': 'answers',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('overview', models.TextField(verbose_name='overview')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=e_learning.models.course_image_upload_to, verbose_name='cover')),
                ('video', models.FileField(blank=True, null=True, upload_to=e_learning.models.course_video_upload_to, verbose_name='promotional video')),
                ('rate', models.FloatField(blank=True, default=0, null=True, verbose_name='rate')),
                ('category', models.CharField(choices=[('finance_accounting', 'Finance & Accounting'), ('development', 'Development'), ('business', 'Business'), ('it_software', 'IT Software'), ('office_productivity', 'Office Productivity'), ('personal_development', 'Personal Development'), ('design', 'Design'), ('marketing', 'Marketing'), ('lifestyle', 'Lifestyle'), ('photography', 'Photography'), ('health_fitness', 'Health Fitness'), ('music', 'Music'), ('teaching_academics', 'Teaching Academics')], max_length=100, verbose_name='category')),
                ('language', models.CharField(max_length=100, verbose_name='language')),
                ('level', models.CharField(choices=[('beginner', 'Beginner Level'), ('intermediate', 'Intermediate Level'), ('expert', 'Expert Level'), ('all', 'All Levels')], max_length=100, verbose_name='level')),
                ('price', models.FloatField(verbose_name='price')),
                ('is_free', models.BooleanField(default=False, verbose_name='is it free')),
                ('is_drift', models.BooleanField(default=True, verbose_name='is it drift')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='question')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.UUIDField(unique=True, verbose_name='user')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.UUIDField(unique=True, verbose_name='user')),
            ],
            options={
                'verbose_name': 'teacher',
                'verbose_name_plural': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answer', to='e_learning.Answer', verbose_name='answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answer', to='e_learning.Question', verbose_name='question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answer', to='e_learning.Student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'student answer',
                'verbose_name_plural': 'student answers',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('objective', models.CharField(max_length=200, verbose_name='objective')),
                ('order', models.SmallIntegerField(verbose_name='section order')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='e_learning.Course', verbose_name='course')),
            ],
            options={
                'verbose_name': 'section',
                'verbose_name_plural': 'sections',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='e_learning.Section', verbose_name='course')),
            ],
            options={
                'verbose_name': 'quiz',
                'verbose_name_plural': 'quizzes',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='e_learning.Quiz', verbose_name='quiz'),
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('text', models.TextField(blank=True, null=True, verbose_name='text')),
                ('video', models.FileField(blank=True, null=True, upload_to=e_learning.models.lecture_video_upload_to, verbose_name='lecture video')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='e_learning.Section', verbose_name='section')),
            ],
            options={
                'verbose_name': 'lecture',
                'verbose_name_plural': 'lectures',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='courses', to='e_learning.Student', verbose_name='student'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='e_learning.Teacher', verbose_name='teacher'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='e_learning.Question', verbose_name='question'),
        ),
    ]
