# Generated by Django 3.0.4 on 2020-03-22 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='object_id')),
                ('action', models.CharField(max_length=10, verbose_name='action')),
                ('device', models.TextField(verbose_name='device')),
                ('language', models.CharField(max_length=100, verbose_name='language')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='content_type_analysis', to='contenttypes.ContentType', verbose_name='content_type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_analysis', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'analytic',
                'verbose_name_plural': 'analytics',
            },
        ),
    ]
